# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs unit tests"
  lane :unit_tests do |options|
    build_type = options[:release] ? "Release" : "Debug"
    gradle(task: "test", build_type: build_type)
  end

  desc "Runs integration tests"
  lane :integration_tests do |options|
  automated_test_emulator_run(
      AVD_setup_path: "fastlane/AVD_setup.json",
      gradle_task: "connected#{options[:build_variant]}AndroidTest"
      )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: 'assemble', build_type: 'Debug')
    crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: 'assemble', build_type: 'Release')
    upload_to_play_store
  end
end
